In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
sales = pd.read_csv("D:/foresight-demand-inventory-intelligence/Raw Datsets/sales_daily.csv")

sku_master = pd.read_csv("D:/foresight-demand-inventory-intelligence/Raw Datsets/sku_master.csv")

calendar = pd.read_csv("D:/foresight-demand-inventory-intelligence/Raw Datsets/calendar.csv")

inventory = pd.read_csv("D:/foresight-demand-inventory-intelligence/Raw Datsets/inventory_snapshots.csv")

In [5]:
print("Sales data:", sales.shape)
print("SKU master:", sku_master.shape)
print("Calendar:", calendar.shape)
print("Inventory:", inventory.shape)

Sales data: (36550, 6)
SKU master: (50, 8)
Calendar: (731, 11)
Inventory: (4800, 8)

In [ ]:
sales.head()

,Snapshot_Date,SKU,Current_Stock,On_Order,Lead_Time_Days,Safety_Stock,Reorder_Point,Inventory_Value
0,2024-01-01,SKU001,16,23,11,7,18,58420.96
1,2024-01-01,SKU002,29,12,4,5,10,163983.40
2,2024-01-01,SKU003,34,23,14,6,20,209060.22
3,2024-01-01,SKU004,34,4,7,5,12,42257.92
4,2024-01-01,SKU005,23,5,5,6,11,170945.89

In [7]:
sku_master.head()

,SKU,Product_Name,Category,Subcategory,Launch_Date,Cost_Price,Selling_Price,Gross_Margin_Per_Unit
0,SKU001,Product 001,Furniture,Chair,2022-04-09,1758.45,3664.05,1905.60
1,SKU002,Product 002,Home Decor,Table,2024-05-01,3867.09,3805.69,-61.40
2,SKU003,Product 003,Kitchen,Cushion,2023-12-22,589.48,8078.23,7488.75
3,SKU004,Product 004,Lighting,Cookware,2023-04-28,1445.74,6861.57,5415.83
4,SKU005,Product 005,Storage,Lamp,2023-04-22,5543.63,9493.22,3949.59

In [8]:
calendar.head()

,date,year,month,quarter,week,day_of_week,is_weekend,season,holiday,is_holiday,promotion_event
0,2024-01-01,2024,1,Q1,1,Monday,0,Winter,NaN,0,NaN
1,2024-01-02,2024,1,Q1,1,Tuesday,0,Winter,NaN,0,NaN
2,2024-01-03,2024,1,Q1,1,Wednesday,0,Winter,NaN,0,NaN
3,2024-01-04,2024,1,Q1,1,Thursday,0,Winter,NaN,0,NaN
4,2024-01-05,2024,1,Q1,1,Friday,0,Winter,NaN,0,NaN

In [9]:
inventory.head()

,Snapshot_Date,SKU,Current_Stock,On_Order,Lead_Time_Days,Safety_Stock,Reorder_Point,Inventory_Value
0,2024-01-01,SKU001,16,23,11,7,18,58420.96
1,2024-01-01,SKU002,29,12,4,5,10,163983.40
2,2024-01-01,SKU003,34,23,14,6,20,209060.22
3,2024-01-01,SKU004,34,4,7,5,12,42257.92
4,2024-01-01,SKU005,23,5,5,6,11,170945.89

In [10]:
print("Sales columns:")
print(sales.columns.tolist())

print("/nSKU Master columns:")
print(sku_master.columns.tolist())

print("/nCalendar columns:")
print(calendar.columns.tolist())

print("/nInventory columns:")
print(inventory.columns.tolist())

Sales columns:
['Date', 'SKU', 'Units_Sold', 'Revenue', 'Price', 'Promotion']
/nSKU Master columns:
['SKU', 'Product_Name', 'Category', 'Subcategory', 'Launch_Date', 'Cost_Price', 'Selling_Price', 'Gross_Margin_Per_Unit']
/nCalendar columns:
['date', 'year', 'month', 'quarter', 'week', 'day_of_week', 'is_weekend', 'season', 'holiday', 'is_holiday', 'promotion_event']
/nInventory columns:
['Snapshot_Date', 'SKU', 'Current_Stock', 'On_Order', 'Lead_Time_Days', 'Safety_Stock', 'Reorder_Point', 'Inventory_Value']

In [ ]:
# Understand the data types
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 36550 entries, 0 to 36549
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Date        36550 non-null  str
 1   SKU         36550 non-null  str
 2   Units_Sold  36550 non-null  int64
 3   Revenue     36550 non-null  float64
 4   Price       36550 non-null  float64
 5   Promotion   36550 non-null  int64
dtypes: float64(2), int64(2), str(2)
memory usage: 1.7 MB

In [12]:
sku_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   SKU                    50 non-null     str
 1   Product_Name           50 non-null     str
 2   Category               50 non-null     str
 3   Subcategory            50 non-null     str
 4   Launch_Date            50 non-null     str
 5   Cost_Price             50 non-null     float64
 6   Selling_Price          50 non-null     float64
 7   Gross_Margin_Per_Unit  50 non-null     float64
dtypes: float64(3), str(5)
memory usage: 3.3 KB

In [15]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             731 non-null    str
 1   year             731 non-null    int64
 2   month            731 non-null    int64
 3   quarter          731 non-null    str
 4   week             731 non-null    int64
 5   day_of_week      731 non-null    str
 6   is_weekend       731 non-null    int64
 7   season           731 non-null    str
 8   holiday          8 non-null      str
 9   is_holiday       731 non-null    int64
 10  promotion_event  75 non-null     str
dtypes: int64(5), str(6)
memory usage: 62.9 KB

In [16]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 4800 entries, 0 to 4799
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Snapshot_Date    4800 non-null   str
 1   SKU              4800 non-null   str
 2   Current_Stock    4800 non-null   int64
 3   On_Order         4800 non-null   int64
 4   Lead_Time_Days   4800 non-null   int64
 5   Safety_Stock     4800 non-null   int64
 6   Reorder_Point    4800 non-null   int64
 7   Inventory_Value  4800 non-null   float64
dtypes: float64(1), int64(5), str(2)
memory usage: 300.1 KB

In [17]:
# check missing values in each dataset

sales.isnull().sum()

Date          0
SKU           0
Units_Sold    0
Revenue       0
Price         0
Promotion     0
dtype: int64

In [18]:
sku_master.isnull().sum()

SKU                      0
Product_Name             0
Category                 0
Subcategory              0
Launch_Date              0
Cost_Price               0
Selling_Price            0
Gross_Margin_Per_Unit    0
dtype: int64

In [20]:
calendar.isnull().sum()

date                 0
year                 0
month                0
quarter              0
week                 0
day_of_week          0
is_weekend           0
season               0
holiday            723
is_holiday           0
promotion_event    656
dtype: int64

In [21]:
inventory.isnull().sum()

Snapshot_Date      0
SKU                0
Current_Stock      0
On_Order           0
Lead_Time_Days     0
Safety_Stock       0
Reorder_Point      0
Inventory_Value    0
dtype: int64

In [22]:
# Check duplicates

print("Sales duplicates:", sales.duplicated().sum())
print("SKU Master duplicates:", sku_master.duplicated().sum())
print("Calendar duplicates:", calendar.duplicated().sum())
print("Inventory duplicates:", inventory.duplicated().sum())

Sales duplicates: 0
SKU Master duplicates: 0
Calendar duplicates: 0
Inventory duplicates: 0

In [23]:
# basic statistics

sales.describe()

         Units_Sold       Revenue         Price     Promotion
count  36550.000000   36550.00000  36550.000000  36550.000000
mean      14.003010   84707.43385   5892.663800      0.102599
std        8.467305   76534.63044   3138.775609      0.303439
min        0.000000       0.00000    663.460000      0.000000
25%        7.000000   27643.70000   3484.090000      0.000000
50%       13.000000   56125.90000   5649.795000      0.000000
75%       20.000000  127954.32000   8516.600000      0.000000
max       56.000000  546977.00000  11642.450000      1.000000

In [24]:
sku_master.describe()

        Cost_Price  Selling_Price  Gross_Margin_Per_Unit
count    50.000000      50.000000              50.000000
mean   3770.729400    5892.663800            2121.934400
std    2025.786477    3170.598793            3784.884812
min     307.060000     663.460000           -5484.320000
25%    1936.910000    3502.567500            -579.570000
50%    3836.845000    5649.795000            1790.025000
75%    5514.770000    8506.780000            4846.322500
max    7748.200000   11642.450000           10224.930000

In [25]:
inventory.describe()

,Current_Stock,On_Order,Lead_Time_Days,Safety_Stock,Reorder_Point,Inventory_Value
count,4800.000000,4800.000000,4800.000000,4800.000000,4800.000000,4.800000e+03
mean,304.143333,213.093750,8.438958,83.152708,211.745417,1.304166e+06
std,280.890448,244.456955,3.488024,70.256045,179.905422,1.741551e+06
min,2.000000,0.000000,3.000000,5.000000,10.000000,2.444200e+03
25%,109.000000,49.000000,5.000000,35.000000,87.000000,2.521855e+05
50%,229.000000,135.000000,8.000000,67.000000,169.000000,6.837389e+05
75%,418.000000,292.000000,11.250000,112.000000,286.000000,1.720023e+06
max,2585.000000,3060.000000,14.000000,746.000000,1661.000000,2.027987e+07

In [26]:
calendar.describe()

              year       month        week  is_weekend  is_holiday
count   731.000000  731.000000  731.000000  731.000000  731.000000
mean   2024.499316    6.519836   26.395349    0.284542    0.010944
std       0.500342    3.451913   15.076278    0.451505    0.104110
min    2024.000000    1.000000    1.000000    0.000000    0.000000
25%    2024.000000    4.000000   13.000000    0.000000    0.000000
50%    2024.000000    7.000000   26.000000    0.000000    0.000000
75%    2025.000000   10.000000   39.000000    1.000000    0.000000
max    2025.000000   12.000000   52.000000    1.000000    1.000000

In [33]:
# unique SKU Level

sales["SKU"].nunique()
sku_master["SKU"].nunique()
inventory["SKU"].nunique()

200

In [34]:
sales.columns.tolist()
sku_master.columns.tolist()
calendar.columns.tolist()
inventory.columns.tolist()

['Snapshot_Date',
 'SKU',
 'Current_Stock',
 'On_Order',
 'Lead_Time_Days',
 'Safety_Stock',
 'Reorder_Point',
 'Inventory_Value']